/* Language
=================*/

var arrLang = {
    "uk": {
        "services": "Services",
        "portfolio": "Portfolio",
        "partners": "Partners",
        "about": "About US",
        "contacts": "Contacts",
        "we": "We are:",
        "all": "All",
        "interior": "Interior",
        "interior 2021": "interior 2021",
        "exterior": "Exterior",
        "exterior 2020": "exterior 2020",
        "decor": "Decor",
        "load more": "LOAD MORE WORK",
        "with best": "We work with the best",
        "radiators": "radiators",
        "read more": "read more",
        "furniture": "furniture",
        "tiles": "tiles",
        "see more": "see more",
        "download en": "download EN",
        "download ua": "download UA",
        "type": "type:",
        "description": "description:",
        "d-p": "Design-project",
        "0": "Detailed information you can download - by clicking the button above. There you will be able to get a complete description of the options that apply to each type of design-project.",
        "01": "If you have additional questions, you can always contact us in a way convenient for you by clicking the button below.",
        "1": "1. Measurements of the existing premises (measurement plan) with bindings of engineering communications;",
        "2": "2. Variants for planning decisions (1-3 options);",
        "3": "3. Plan after redevelopment;",
        "4": "4. Plan of construction dismantling and installation;",
        "5": "5. Furniture placement plan (1-3 options);",
        "6": "6. Floor plan with layout of materials;",
        "7": "7. Plan of the ceiling with the layout of materials;",
        "8": "8. Lighting placement plan;",
        "9": "9. Layout of switches;",
        "10": "10. Socket placement plan;",
        "11": "11. Plumbing placement plan;",
        "12": "12. Sweep the walls with the layout of materials;",
        "13": "13. Air conditioning scheme;",
        "14": "14. Layout of kitchen appliances and equipment;",
        "15": "15. Layout of plumbing fixtures and equipment;",
        "16": "16. Specification of luminaries with indication of model and store;",
        "17": "17. Specification of decorative materials indicating the model and store;",
        "18": "18. Specification of furniture indicating the dimensions and the store;",
        "19": "19. Specification of electrical equipment;",
        "20": "20. Visualization of the interior in the program 3D Max (up to 3 images for each room);",
        "21": "21. Layout of cameras in 3D Max with reference to the plan;",
        "22": "Author's supervision - is carried out at all stages of construction / repair works and includes the following actions:",
        "23": "- visit to the object 3 times a week, lasting 1 hour;",
        "24": "- control of conformity of performance of works according to the design project;",
        "25": "- consultations for workers;",
        "26": "- keeping a journal of author's supervision;",
        "27": "- control over the implementation of instructions entered in the journal;",
        "28": "- taking operational measures to eliminate the identified discrepancies according to the working documentation;",
        "29": "- complete set - if (finishing materials, furniture, lighting, plumbing, etc.) are purchased from our partners.",
        "y1": "Very professional and organized company. I ordered a design project for my apartment - everything was done as I wanted and imagined and even better. Provided useful suggestions and ideas for the organization of space at the design stage.",
        "y2": "I was so pleased with our cooperation that I decided to order the implementation and it was the right decision.",
        "y3": "Thanks Vision Group Design!!!",
        "ab 1": "Vision Group Design has been designing interiors and exteriors since 2017. We have formed teams of narrow-profile craftsmen who perform work of various levels of complexity, from disassembly to final decoration and installation of furniture.",
        "ab 2": "Vision Group Design has completed more than 300 individual projects for our clients and implemented more than 150 projects. Our clients are also international companies, government agencies and private companies.",
        "ab 3": "The company's employees are always focused on high-quality and clear performance of tasks in order for our client to be satisfied with the result.",
        "cordivari-t": "Cordivari Srl is a leading Italian manufacturer of heat accumulators, boilers, compressed air tanks, designer radiators, solar heating systems, air ducts and food containers.",
        "adk-t": "Furniture Factory ADK ™ modular systems, corner sofas, sofa beds, armchairs and other upholstered furniture.",
        "kerama-t": "Kerama Market - is one of the largest distributors of tiles and plumbing in Ukraine, the official representative and direct importer of products from 80 factories around the world.",
        "call or mail": "CALL ME OR SEND MAIL",
        "send": "SEND",
        "cottage": "Cottage",
        "client": "Client",
        "private person": "Private person",
        "cottage 1": "The story that happened during the first quarantine. We were approached by a client who had an old cottage, with a desire to visualize his plan!",
        "cottage 2": "And the idea was to expand the house and create conditions for comfortable living for a family with two children.",
        "cottage 3": "We visualized the client's ideas for interior and exterior design and helped organize the space.",
        "cottage 4": "For the customer and his family, this resuscitation of the cottage has become a pleasant process in which even children were enthusiastically involved, and warm relations in the process of cooperation - charged us!",
        "shop l": "Shop - Fox Lingerie",
        "shop 1": "20 days 24/7, this is the deadline for the implementation of the design project of the Ukrainian branded lingerie store Fox Lingerie.",
        "shop 2": "During this period, it was necessary to renovate the store, which the previous tenant left in a terrible state, cutting off all communications at the root in the walls of the hole, and the convector - literally pulled from the ventilation and heating systems.",
        "shop 3": "We can still add a lot of descriptions of what happened, but we'd better share what we did",
        "house in the village": "House in the village",
        "exterior 2017": "exterior 2017",
        "village 1": "Implementation of our house project in a village near Lviv.",
        "village 2": "A small comfortable house where only nature is around, a place where you can feel yourself.",
        "village 3": "Large panoramic windows give a feeling of harmony with nature.",
        "decor 2022": "Decor 2022",
        "idea": "Idea",
        "for everyone": "for everyone",
        "idea 1": "We share with you interesting and bright ideas.",
        "idea 2": "Get inspired and use for your own purposes.",
        "Sokilnyky": "Sokilnyky",
        "Interior design 2020": "Interior design 2020",
        "sok 1": "Organizing a kitchen space is easy! 😎",
        "sok 2": "Key positions on which we create and implement our projects:",
        "sok 3": "✔ well-thought-out design project;",
        "sok 4": "✔ correctly and accurately connected communications (water, sewerage, electricity, ventilation, gas);",
        "sok 5": "✔ selection of materials (facades, housing, countertops, accessories).",
        "sok 6": "Photo of the implementation of our turnkey project.",
        "Interior design 2021": "Interior design 2021",
        "sok1": "In this project, each square meter is maximally used and at the same time the feeling of space is preserved. The quality of materials, ergonomics, functionality and conciseness - all this is a guarantee of comfort.",
        "sok2": "This project is under implementation - expect a photo report soon in which we will show all the nuances that arise during the implementation, as well as many useful solutions.",
        "Category: Interior": "Category: Interior",
        "Category: Decor": "Category: Decor",
        "Flat": "Flat",
        "Kitchen": "Kitchen",
        "Other": "Other",
        "House": "House",
        "Shop": "Shop",
    },
    "ua": {
        "services": "Сервіси",
        "portfolio": "Портфоліо",
        "partners": "Партнери",
        "about": "Про нас",
        "contacts": "Контакти",
        "we": "Ми в соцмережах:",
        "all": "все",
        "interior": "інтер'єр",
        "interior 2021": "інтер'єр 2021",
        "exterior": "екстер'єр",
        "exterior 2020": "екстер'єр 2020",
        "decor": "декор",
        "load more": "Завантажити більше",
        "with best": "Ми працюємо з найкращими",
        "radiators": "радіатори",
        "read more": "дізнатись більше",
        "furniture": "меблі",
        "tiles": "плитка",
        "see more": "дивитись більше",
        "download en": "завантажити EN",
        "download ua": "завантажити UA",
        "type": "тип:",
        "description": "опис:",
        "d-p": "дизайн-прект",
        "0": "Детальну інформацію, ви можете завантажити - натиснуваши кнопку зверху. Там ти зможеш отримати повний опис опцій, які відносяться до кожного типу дизайн-проекту.",
        "01": "Якщо виникнуть додаткові запитання ти завжди можеш зв'язатись з нами у зручний для тебе спосіб натиснувши кнопку внизу.",
        "1": "1. Обміри існуючих приміщень (план замірів) з прив'язками інженерних комунікацій;",
        "2": "2. Планувальні рішення (1-3 варіанти);",
        "3": "3. План після перепланування;",
        "4": "4. План будівельного демонтажу та монтажу;",
        "5": "5. План розміщення меблів (1-3 варіанти);",
        "6": "6. План підлоги з розкладкою матеріалів;",
        "7": "7. План стелі з розкладкою матеріалів;",
        "8": "8. План освітлення;",
        "9": "9. План розміщення вимикачів;",
        "10": "10. План розміщення розеток;",
        "11": "11. План розміщення сантехніки;",
        "12": "12. Розгортки стін з розкладкою матеріалів;",
        "13": "13. Схема кондиціонування;",
        "14": "14. Розміщення кухонної техніки та обладнання;",
        "15": "15. Розміщення сантехніки та обладнання;",
        "16": "16. Специфікація світильників із зазначенням моделі та магазину;",
        "17": "17. Специфікація декоративних матеріалів із зазначенням моделі та магазину;",
        "18": "18. Специфікація меблів із зазначенням розмірів і магазину;",
        "19": "19. Специфікація електрообладнання;",
        "20": "20. Візуалізація інтер'єру в програмі 3D Max (до 3 зображень на кожну кімнату);",
        "21": "21. Розміщення камер в 3D Max з посиланням на план;",
        "22": "Авторський нагляд - здійснюється на всіх етапах будівельно-ремонтних робіт і включає наступні дії:",
        "23": "- відвідування об’єкта 3 рази на тиждень, тривалістю по 1 год;",
        "24": "- контроль відповідності виконання робіт за проектом;",
        "25": "- консультації для працівників;",
        "26": "- ведення журналу авторського нагляду;",
        "27": "- контроль за виконанням приписів, внесених до журналу;",
        "28": "- вживання оперативних заходів щодо усунення виявлених невідповідностей згідно з робочою документацією;",
        "29": "- комплектація - якщо (оздоблювальні матеріали, меблі, освітлення, сантехніка тощо) закуповуються у наших партнерів.",
        "y1": "Дуже професійна та організована компанія. Замовила дизайн-проект своєї квартири - все зроблено так, як я хотіла і уявляла і навіть краще. Надали корисні пропозиції та ідеї щодо організації простору на етапі проектування.",
        "y2": "Я була настільки задоволена нашою співпрацею, що вирішила замовити впровадження, і це було правильне рішення.",
        "y3": "Дякую Vision Group Design!!!",
        "ab 1": "Vision Group Design займається проектуванням інтер’єрів та екстер’єрів з 2017 року. Ми сформували бригади вузькопрофільних майстрів, які виконують роботи різного рівня складності, від демонтажних робіт до остаточного оздоблення та встановлення меблів.",
        "ab 2": "Vision Group Design виконала понад 300 індивідуальних проектів для наших клієнтів та реалізувала понад 150 проектів. Нашими клієнтами є також міжнародні компанії, державні установи та приватні компанії.",
        "ab 3": "Співробітники компанії завжди націлені на якісне та чітке виконання поставлених завдань, щоб наш клієнт був задоволений результатом.",
        "cordivari-t": "Cordivari Srl є провідним італійським виробником теплових акумуляторів, котлів, резервуарів стисненого повітря, дизайнерських радіаторів, систем сонячного опалення, повітропроводів та харчових контейнерів.",
        "adk-t": "Меблева фабрика ADK™ модульні системи, кутові дивани, дивани-ліжка, крісла та інші м'які меблі.",
        "kerama-t": "«Керама Маркет» — один з найбільших дистриб’юторів плитки та сантехніки в Україні, офіційний представник та прямий імпортер продукції з 80 заводів по всьому світу.",
        "call or mail": "БУДЬ З НАМИ НА ЗВ'ЯЗКУ",
        "send": "ВІДПРАВИТИ",
        "cottage": "Котедж",
        "client": "Клієнт",
        "private person": "Приватна особа",
        "cottage 1": "Історія, яка сталася під час першого карантину. До нас звернувся клієнт, який мав старий котедж, з бажанням візуалізувати його план!",
        "cottage 2": "А ідея полягала в тому, щоб розширити будинок і створити умови для комфортного проживання сім’ї з двома дітьми.",
        "cottage 3": "Ми візуалізували ідеї клієнта щодо дизайну інтер’єру та екстер’єру та допомогли організувати простір.",
        "cottage 4": "Для замовника та його родини ця реанімація котеджу стала приємним процесом, до якого з ентузіазмом були залучені навіть діти, а теплі стосунки в процесі співпраці – зар'ядили нас!",
        "shop l": "Магазин - Fox Lingerie",
        "shop 1": "20 днів 24/7, це термін реалізації дизайн-проекту українського брендового магазину жіночої білизни Fox Lingerie.",
        "shop 2": "За цей період довелося відремонтувати магазин, який попередній орендар залишив у жахливому стані, відрізавши всі комунікації під корінь, у стінах дири, а конвектор – буквально вирвали із систем вентиляції та опалення.",
        "shop 3": "Ми ще можемо додати багато описів того, що сталося, але нам краще поділитися тим, що ми зробили",
        "house in the village": "Будинок у селі",
        "exterior 2017": "екстер'єр 2017",
        "village 1": "Реалізація проекту нашого будинку в селі під Львовом.",
        "village 2": "Маленький затишний будиночок, де навколо лише природа, місце, де можна відчути себе.",
        "village 3": "Великі панорамні вікна створюють відчуття гармонії з природою.",
        "decor 2022": "Декор 2022",
        "idea": "Ідея",
        "for everyone": "для кожного",
        "idea 1": "Ділимося з вами цікавими та яскравими ідеями.",
        "idea 2": "Надихайтеся та використовуйте у своїх цілях.",
        "Sokilnyky": "Сокільники",
        "Interior design 2020": "Дизайн інтер'єру 2020",
        "sok 1": "Організувати кухонний простір легко! 😎",
        "sok 2": "Ключові позиції, на яких ми створюємо та реалізуємо наші проекти:",
        "sok 3": "✔ продуманий дизайн-проект;",
        "sok 4": "✔ правильно і акуратно підключені комунікації (вода, каналізація, електрика, вентиляція, газ);",
        "sok 5": "✔ підбір матеріалів (фасади, корпус, стільниці, фурнітура).",
        "sok 6": "Фото реалізації нашого проекту під ключ.",
        "Interior design 2021": "Дизайн інтер'єру 2021",
        "sok1": "У цьому проекті максимально використано кожен квадратний метр і при цьому збережено відчуття простору. Якість матеріалів, ергономіка, функціональність і лаконічність - все це запорука комфорту.",
        "sok2": "Цей проект на стадії реалізації – незабаром чекайте фотозвіт, в якому ми покажемо всі нюанси, що виникають під час реалізації, а також багато корисних рішень.",
        "Category: Interior": "Категорія: Інтер'єр",
        "Category: Decor": "Категорія: Декор",
        "Category: Exterior": "Категорія: Екстер'єр",
        "Flat": "Квартира",
        "Kitchen": "Кухня",
        "Other": "Інше",
        "House": "Будинок",
        "Shop": "Магазин",
    },
};

$(function() {
    $(".translate").click(function() {
        var lang = $(this).attr("id");

        $(".lang").each(function(index, item) {
            $(this).text(arrLang[lang][$(this).attr("key")]);
        });
    });
    
});
